name: "Vultr"

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: sidxdev/cloudtask
      with:
        vendor: vultr
        api_key: ${{secrets.vultr_api_key}}
        task: |
          echo 'Hello World'
